import React, { useState } from 'react';
import { View, Text, TouchableOpacity, ScrollView, StyleSheet } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from '@/hooks/useTheme';

const CODE_LINES = [
  { text:'# ─────────────────────────────────────────', c:'#4A5568' },
  { text:'# SIGNAL Strategy  ·  RSI + EMA Crossover',  c:'#68D391' },
  { text:'# Generated by SIGNAL App  ·  Jun 2026',     c:'#68D391' },
  { text:'# Exchange: NSE  ·  Stocks: RELIANCE, HDFC', c:'#68D391' },
  { text:'# ─────────────────────────────────────────', c:'#4A5568' },
  { text:'',                                            c:'#ccc' },
  { text:'import pandas as pd',                         c:'#79C0FF' },
  { text:'import numpy as np',                          c:'#79C0FF' },
  { text:'',                                            c:'#ccc' },
  { text:'RSI_LOW, RSI_HIGH = 35, 70',                 c:'#F6C90E' },
  { text:'EMA_FAST, EMA_SLOW = 20, 50',                c:'#F6C90E' },
  { text:'STOP_LOSS, TARGET = 2.5, 6.0',               c:'#F6C90E' },
  { text:'',                                            c:'#ccc' },
  { text:'def rsi(close, n=14):',                       c:'#FF7D46' },
  { text:'    d = close.diff()',                         c:'#E2E8F0' },
  { text:'    g = d.clip(lower=0).rolling(n).mean()',   c:'#E2E8F0' },
  { text:'    l = (-d.clip(upper=0)).rolling(n).mean()',c:'#E2E8F0' },
  { text:'    return 100 - (100 / (1 + g / l))',        c:'#E2E8F0' },
  { text:'',                                            c:'#ccc' },
  { text:'def signal(df):',                             c:'#FF7D46' },
  { text:'    r    = rsi(df["close"])',                  c:'#E2E8F0' },
  { text:'    fast = df["close"].ewm(span=EMA_FAST).mean()', c:'#E2E8F0' },
  { text:'    slow = df["close"].ewm(span=EMA_SLOW).mean()', c:'#E2E8F0' },
  { text:'    cross = fast.iloc[-1] > slow.iloc[-1] \\', c:'#E2E8F0' },
  { text:'        and fast.iloc[-2] <= slow.iloc[-2]',   c:'#E2E8F0' },
  { text:'    if r.iloc[-1] < RSI_LOW and cross:',       c:'#E2E8F0' },
  { text:'        return "BUY"',                          c:'#68D391' },
  { text:'    if r.iloc[-1] > RSI_HIGH:',                 c:'#E2E8F0' },
  { text:'        return "SELL"',                         c:'#FC8181' },
  { text:'    return "HOLD"',                             c:'#E2E8F0' },
];

const METRICS = [
  { l:'Returns', v:'+24.3%', ck:'grn' },
  { l:'Sharpe',  v:'1.84',   ck:'bluL' },
  { l:'Win Rate',v:'64%',    ck:'grn' },
  { l:'Max DD',  v:'-8.2%',  ck:'red' },
];

const LANGS = ['Python','Pine'];

export default function CodeGen() {
  const { T, ACC } = useTheme();
  const router = useRouter();
  const [copied, setCopied] = useState(false);
  const [lang, setLang] = useState('Python');

  const handleCopy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  };

  return (
    <SafeAreaView style={[s.safe, { backgroundColor: T.bg }]}>
      {/* Header */}
      <View style={s.topBar}>
        <View style={s.titleGroup}>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={[s.backTxt, { color: T.dim }]}>‹</Text>
          </TouchableOpacity>
          <View>
            <Text style={[s.h1, { color: T.txt }]}>Generated Code</Text>
            <Text style={[s.sub, { color: T.dim }]}>RSI + EMA Crossover · Python</Text>
          </View>
        </View>
        <View style={s.langToggle}>
          {LANGS.map((l, i) => (
            <TouchableOpacity key={l} onPress={() => setLang(l)}
              style={[s.langBtn, { backgroundColor: l === lang ? `${ACC.blu}20` : T.surf2, borderColor: l === lang ? ACC.blu : T.bdr }]}>
              <Text style={[s.langTxt, { color: l === lang ? ACC.bluL : T.dim }]}>{l}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Code block — always dark #0D1117 */}
        <View style={[s.codeBlock, { margin: 14, borderRadius: 13 }]}>
          <View style={s.codeBar}>
            <Text style={s.fileName}>signal_rsi_ema.py</Text>
            <TouchableOpacity onPress={handleCopy}
              style={[s.copyBtn, { backgroundColor: copied ? `${ACC.grn}22` : `${ACC.blu}22`, borderColor: copied ? ACC.grn : ACC.blu }]}>
              <Text style={[s.copyTxt, { color: copied ? ACC.grn : ACC.bluL }]}>
                {copied ? '✓ Copied!' : '⎘ Copy'}
              </Text>
            </TouchableOpacity>
          </View>
          <ScrollView horizontal showsHorizontalScrollIndicator={false}>
            <View style={s.codeLines}>
              {CODE_LINES.map((line, i) => (
                <Text key={i} style={[s.codeLine, { color: line.c }]}>
                  {line.text || ' '}
                </Text>
              ))}
            </View>
          </ScrollView>
        </View>

        {/* Backtest results */}
        <View style={s.metricsSection}>
          <Text style={[s.metricsLabel, { color: T.dim }]}>1Y BACKTEST RESULTS</Text>
          <View style={s.metricsGrid}>
            {METRICS.map(m => (
              <View key={m.l} style={[s.metricCard, { backgroundColor: T.surf, borderColor: T.bdr }]}>
                <Text style={[s.metricVal, { color: ACC[m.ck as keyof typeof ACC] }]}>{m.v}</Text>
                <Text style={[s.metricLbl, { color: T.dim }]}>{m.l}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={s.cta}>
          <TouchableOpacity onPress={() => router.push('/(app)/algo/deploy')}
            style={[s.deployBtn, { backgroundColor: ACC.org }]}>
            <Text style={s.deployTxt}>Deploy Script →</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe:          { flex: 1 },
  topBar:        { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', padding: 14, paddingBottom: 8 },
  titleGroup:    { flexDirection: 'row', alignItems: 'center', gap: 8 },
  backTxt:       { fontSize: 24, fontWeight: '300' },
  h1:            { fontSize: 22, fontWeight: '800' },
  sub:           { fontSize: 12, marginTop: 2 },
  langToggle:    { flexDirection: 'row', gap: 6 },
  langBtn:       { paddingHorizontal: 11, paddingVertical: 5, borderRadius: 8, borderWidth: 1 },
  langTxt:       { fontSize: 11.5, fontWeight: '700' },
  codeBlock:     { overflow: 'hidden', backgroundColor: '#0D1117', borderWidth: 1, borderColor: '#21262D' },
  codeBar:       { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 8, paddingHorizontal: 12, backgroundColor: '#161B22', borderBottomWidth: 1, borderBottomColor: '#21262D' },
  fileName:      { fontSize: 11, color: '#8B949E', fontFamily: 'monospace' },
  copyBtn:       { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 7, borderWidth: 1 },
  copyTxt:       { fontSize: 11.5, fontWeight: '700' },
  codeLines:     { padding: 10, paddingHorizontal: 14 },
  codeLine:      { fontSize: 10.5, lineHeight: 17, fontFamily: 'monospace' },
  metricsSection:{ padding: 14, paddingTop: 8 },
  metricsLabel:  { fontSize: 11, fontWeight: '700', letterSpacing: 0.5, marginBottom: 8 },
  metricsGrid:   { flexDirection: 'row', gap: 8 },
  metricCard:    { flex: 1, padding: 9, borderRadius: 12, borderWidth: 1, alignItems: 'center' },
  metricVal:     { fontSize: 16, fontWeight: '900' },
  metricLbl:     { fontSize: 10, marginTop: 2 },
  cta:           { paddingHorizontal: 14, paddingBottom: 24 },
  deployBtn:     { height: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  deployTxt:     { color: '#fff', fontSize: 15, fontWeight: '700' },
});
